Repository Theseus-Aegis/TheseusServices, pull requests merged in 2018-10, with the labels that each got.

#86 Fix error line numbers being wrong
  extras/blank/functions/fnc_empty.sqf
Labels: bug fix

#87 Add french translations for all modules
  addons/backpacks/stringtable.xml
  addons/glasses/stringtable.xml
  addons/headgear/stringtable.xml
  addons/main/stringtable.xml
  addons/units/stringtable.xml
  addons/vehicles/stringtable.xml
  addons/vests/stringtable.xml
  addons/weapons/stringtable.xml
  optionals/variants_bwa3/stringtable.xml
  optionals/variants_melb/stringtable.xml
Labels: translation

#88 Fix german and japanese entries for a variant of uniform
  addons/units/stringtable.xml
Labels: translation

#90 Use shorter requiredAddons (A3 load order)
  addons/main/config.cpp
Labels: enhancement, task

#91 Update/Fix BWA3 Eagle IV variants for BWA3 v2.0
  optionals/variants_bwa3/CfgVehicles.hpp
  optionals/variants_bwa3/stringtable.xml
Labels: bug fix, enhancement, task

#92 Add custom Theseus license plate to BWA3 Eagle IV variants
  optionals/variants_bwa3/CfgVehicles.hpp
  optionals/variants_bwa3/data/bwa3_normteile_co.paa
Labels: enhancement
