Repository Theseus-Aegis/TheseusServices, pull requests merged in 2018-12, with the labels that each got.

#89 Finished the German translation, spellcheck
  addons/backpacks/stringtable.xml
  addons/glasses/stringtable.xml
  addons/headgear/stringtable.xml
  addons/vehicles/stringtable.xml
  addons/vests/stringtable.xml
  addons/weapons/stringtable.xml
  optionals/variants_bwa3/stringtable.xml
  optionals/variants_melb/stringtable.xml
Labels: translation

#93 Add Theseus Beret
  addons/headgear/CfgVehicles.hpp
  addons/headgear/CfgWeapons.hpp
  addons/headgear/UI/hat_beret_blacklogo_ca.paa
  addons/headgear/config.cpp
  addons/headgear/data/hat_beret_blacklogo_co.paa
  addons/headgear/stringtable.xml
Labels: feature request

#94 Fix Theseus Beret
  addons/headgear/CfgVehicles.hpp
  addons/headgear/CfgWeapons.hpp
Labels: bug fix
