Repository Theseus-Aegis/TheseusServices, pull requests merged in 2019-08, with the labels that each got.

#111 Add Polaris retextures and White Heavy Plate Carrier
  addons/main/script_macros.hpp
  addons/vehicles/CfgVehicles.hpp
  addons/vehicles/README.md
  addons/vehicles/UI/Polaris_AT_Black.jpg
  addons/vehicles/UI/Polaris_AT_Green.jpg
  addons/vehicles/UI/Polaris_AT_Tan.jpg
  addons/vehicles/UI/Polaris_Armed_Black.jpg
  addons/vehicles/UI/Polaris_Armed_Green.jpg
  addons/vehicles/UI/Polaris_Armed_Tan.jpg
  addons/vehicles/UI/Polaris_Black.jpg
  addons/vehicles/UI/Polaris_Green.jpg
  addons/vehicles/UI/Polaris_Tan.jpg
  addons/vehicles/config.cpp
  addons/vehicles/data/polaris_black_adds_co.paa
  addons/vehicles/data/polaris_black_atlauncher_co.paa
  addons/vehicles/data/polaris_black_attube_co.paa
  addons/vehicles/data/polaris_black_ext01_co.paa
  addons/vehicles/data/polaris_black_ext02_co.paa
  addons/vehicles/data/polaris_black_ext03_co.paa
  addons/vehicles/data/polaris_tan_adds_co.paa
  addons/vehicles/data/polaris_tan_atlauncher_co.paa
  addons/vehicles/data/polaris_tan_attube_co.paa
  addons/vehicles/data/polaris_tan_ext01_co.paa
  addons/vehicles/data/polaris_tan_ext02_co.paa
  addons/vehicles/data/polaris_tan_ext03_co.paa
  addons/vehicles/stringtable.xml
  addons/vests/CfgVehicles.hpp
  addons/vests/CfgWeapons.hpp
  addons/vests/UI/vest_platecarrierheavy_white_ca.paa
  addons/vests/config.cpp
  addons/vests/data/vest_platecarrierheavy_white_co.paa
  addons/vests/stringtable.xml
  optionals/variants_bwa3/CfgVehicles.hpp
  optionals/variants_melb/CfgVehicles.hpp
Labels: feature request

#114 Remove custom vests ItemInfo (cargo size and mass)
  addons/vests/CfgWeapons.hpp
Labels: enhancement

#115 Fix Plate Carrier retextures (regression)
  addons/vests/CfgVehicles.hpp
  addons/vests/CfgWeapons.hpp
Labels: bug fix, enhancement

#116 Fix Polaris DAGOR vehicles not visible in Zeus
  addons/vehicles/CfgVehicles.hpp
Labels: bug fix
