Repository Theseus-Aegis/TheseusServices, pull requests merged in 2019-06, with the labels that each got.

#101 Add Compass, Map and Watch to contractor units
  addons/units/CfgVehicles_PublicUnits.hpp
  addons/units/script_component.hpp
Labels: bug fix

#103 New Uniforms
  addons/units/CfgVehicles.hpp
  addons/units/CfgVehicles_GroundItems.hpp
  addons/units/CfgVehicles_HelperUnits.hpp
  addons/units/CfgWeapons.hpp
  addons/units/UI/uniform_combat_ls_cbps_bp_ca.paa
  addons/units/UI/uniform_combat_ls_cdes_tp_ca.paa
  addons/units/UI/uniform_combat_ls_cdfs_tgp_ca.paa
  addons/units/UI/uniform_combat_ls_cles_tp_ca.paa
  addons/units/UI/uniform_combat_ls_clfs_gp_ca.paa
  addons/units/UI/uniform_combat_rs_cbps_bp_ca.paa
  addons/units/UI/uniform_combat_rs_cdes_tp_ca.paa
  addons/units/UI/uniform_combat_rs_cdfs_tgp_ca.paa
  addons/units/UI/uniform_combat_rs_cles_tp_ca.paa
  addons/units/UI/uniform_combat_rs_clfs_gp_ca.paa
  addons/units/config.cpp
  addons/units/data/uniform_combat_cbps_bp_bb_co.paa
  addons/units/data/uniform_combat_cdbs_gp_tb_co.paa
  addons/units/data/uniform_combat_cdes_tp_tb_co.paa
  addons/units/data/uniform_combat_cdfs_gp_tb_co.paa
  addons/units/data/uniform_combat_clbs_gp_bb_co.paa
  addons/units/data/uniform_combat_cles_tp_bb_co.paa
  addons/units/data/uniform_combat_clfs_gp_bb_co.paa
  addons/units/data/uniform_combat_clrs_tp_bb_co.paa
  addons/units/data/uniform_combat_cps_bp_bb_co.paa
  addons/units/stringtable.xml
Labels: feature request

#104 Quote all strings properly (HEMTT/armake2 warnings)
  addons/headgear/CfgVehicles.hpp
  addons/main/CfgMods.hpp
  addons/main/script_macros.hpp
  addons/units/CfgGroups.hpp
  addons/units/CfgVehicles_HelperUnits.hpp
  addons/units/CfgVehicles_PublicUnits.hpp
  addons/vehicles/CfgVehicles.hpp
  build.bat
  optionals/variants_bwa3/CfgVehicles.hpp
  optionals/variants_melb/CfgVehicles.hpp
  optionals/variants_melb/data/melb_clear_ext.rvmat
Labels: enhancement

#106 Set "Throw" and "Put" to end of weapons array
  addons/units/CfgVehicles_PublicUnits.hpp
  optionals/weapons_hlc/CfgVehicles.hpp
  optionals/weapons_rhs_usf/CfgVehicles.hpp
Labels: bug fix
