Repository Theseus-Aegis/TheseusServices, pull requests merged in 2020-08, with the labels that each got.

#139 Various texture improvements & additions
  addons/backpacks/CfgVehicles.hpp
  addons/backpacks/UI/backpack_assaultexpanded_rgr_ca.paa
  addons/backpacks/UI/backpack_assaultpack_rgr_ca.paa
  addons/backpacks/config.cpp
  addons/backpacks/data/backpack_assaultexpanded_rgr_main_co.paa
  addons/backpacks/data/backpack_kitbag_medic_rgr_co.paa
  addons/backpacks/data/backpack_kitbag_rgr_co.paa
  addons/backpacks/stringtable.xml
  addons/headgear/UI/cap_backwards_tan_ca.paa
  addons/headgear/UI/cap_earpiece_tanlogo_ca.paa
  addons/headgear/UI/cap_tanlogo_ca.paa
  addons/headgear/data/cap_blacklogo_co.paa
  addons/headgear/data/cap_headphones_blacklogo_co.paa
  addons/headgear/data/cap_tanlogo_co.paa
  addons/insignias/CfgUnitInsignia.hpp
  addons/insignias/data/willworkforammo.paa
  addons/vests/CfgVehicles.hpp
  addons/vests/CfgWeapons.hpp
  addons/vests/UI/vest_platecarrier_rgr_ca.paa
  addons/vests/data/tacs_Vest_PlateCarrier_rgr_co.paa
  addons/vests/data/vest_platecarrier_black_co.paa
  addons/vests/data/vest_platecarrier_coyote_co.paa
  addons/vests/data/vest_platecarrier_green_co.paa
  addons/vests/data/vest_platecarrier_khaki_co.paa
  addons/vests/data/vest_platecarrier_marpat_co.paa
  addons/vests/data/vest_platecarrier_rgr_co.paa
  addons/vests/data/vest_platecarrier_white_co.paa
  addons/vests/data/vest_platecarrierheavy_black_co.paa
  addons/vests/data/vest_platecarrierheavy_coyote_co.paa
  addons/vests/data/vest_platecarrierheavy_green_co.paa
  addons/vests/data/vest_platecarrierheavy_white_co.paa
  addons/vests/stringtable.xml
Labels: enhancement, feature request

#140 Fix Backpack Texture Filenames & Update RGR Plate Carrier Texture
  addons/backpacks/CfgVehicles.hpp
  addons/backpacks/data/backpack_assaultexpanded_rgr_co.paa
  addons/backpacks/data/backpack_assaultexpanded_tan_co.paa
  addons/backpacks/data/backpack_assaultexpanded_white_co.paa
  addons/vests/data/tacs_Vest_PlateCarrier_rgr_co.paa
  addons/vests/data/vest_platecarrier_rgr_co.paa
Labels: enhancement

#141 Fix RGR Assault Pakc texture path
  addons/backpacks/CfgVehicles.hpp
Labels: bug fix
