Repository Theseus-Aegis/TheseusServices, pull requests merged in 2020-11, with the labels that each got.

#142 Update blank component
  extras/blank/README.md
  extras/blank/config.cpp
  extras/blank/functions/fnc_empty.sqf
  extras/blank/functions/script_component.hpp
  extras/blank/script_component.hpp
Labels: tools

#145 Integrate more DADPAT Uniforms
  addons/units/CfgVehicles_GroundItems.hpp
  addons/units/CfgVehicles_HelperUnits.hpp
  addons/units/CfgWeapons.hpp
  addons/units/UI/uniform_plaid_bb_ly_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_bp_lpp_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_jp_cb_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_jp_gy_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_jp_lp_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_jp_ro_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_jp_rt_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_cb_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_gy_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_lp_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_lpp_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_ly_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_ro_bp_bb_ca.paa
  addons/units/UI/uniform_plaid_sp_rt_bp_bb_ca.paa
  addons/units/config.cpp
  addons/units/data/uniform_plaid_denim_cb_bp_bb_co.paa
  addons/units/data/uniform_plaid_denim_gy_bp_bb_co.paa
  addons/units/data/uniform_plaid_denim_lp_bp_bb_co.paa
  addons/units/data/uniform_plaid_denim_lpp_bp_bb_co.paa
  addons/units/data/uniform_plaid_denim_ly_bp_bb_co.paa
  addons/units/data/uniform_plaid_denim_ro_bp_bb_co.paa
  addons/units/data/uniform_plaid_denim_rt_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_cb_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_gy_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_lp_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_lpp_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_ly_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_ro_bp_bb_co.paa
  addons/units/data/uniform_plaid_shorts_rt_bp_bb_co.paa
  addons/units/stringtable.xml
Labels: feature request

#144 Add Retextures to Contact Vests & Helmets
  addons/headgear/CfgVehicles.hpp
  addons/headgear/CfgWeapons.hpp
  addons/headgear/UI/helmet_modular_au_ca.paa
  addons/headgear/UI/helmet_modular_black_ca.paa
  addons/headgear/UI/helmet_modular_chops_au_ca.paa
  addons/headgear/UI/helmet_modular_chops_black_ca.paa
  addons/headgear/UI/helmet_modular_chops_coyote_ca.paa
  addons/headgear/UI/helmet_modular_chops_fg_ca.paa
  addons/headgear/UI/helmet_modular_chops_green_ca.paa
  addons/headgear/UI/helmet_modular_coyote_ca.paa
  addons/headgear/UI/helmet_modular_ear_au_ca.paa
  addons/headgear/UI/helmet_modular_ear_black_ca.paa
  addons/headgear/UI/helmet_modular_ear_coyote_ca.paa
  addons/headgear/UI/helmet_modular_ear_fg_ca.paa
  addons/headgear/UI/helmet_modular_ear_green_ca.paa
  addons/headgear/UI/helmet_modular_fg_ca.paa
  addons/headgear/UI/helmet_modular_green_ca.paa
  addons/headgear/config.cpp
  addons/headgear/data/helmet_modular_au_co.paa
  addons/headgear/data/helmet_modular_black_co.paa
  addons/headgear/data/helmet_modular_coyote_co.paa
  addons/headgear/data/helmet_modular_fg_co.paa
  addons/headgear/data/helmet_modular_green_co.paa
  addons/headgear/data/helmet_modular_rgr_co.paa
  addons/headgear/stringtable.xml
  addons/vests/CfgVehicles.hpp
  addons/vests/CfgWeapons.hpp
  addons/vests/UI/vest_modular_black_ca.paa
  addons/vests/UI/vest_modular_coyote_ca.paa
  addons/vests/config.cpp
  addons/vests/data/vest_modular_black_co.paa
  addons/vests/data/vest_modular_coyote_co.paa
  addons/vests/stringtable.xml
Labels: feature request

#147 Arcadian - Set fording depth
  optionals/arcadian/CfgVehicles.hpp
Labels: enhancement

#146 Expand F2000 Series to EGLM/Tactical Variants
  addons/weapons/CfgVehicles.hpp
  addons/weapons/CfgWeapons.hpp
  addons/weapons/UI/mk20_eglm_ca.paa
  addons/weapons/UI/mk20c_blackcamo_ca.paa
  addons/weapons/config.cpp
  addons/weapons/stringtable.xml
Labels: feature request

#148 Arcadian - Upgrade headlights to LED
  optionals/arcadian/CfgVehicles.hpp
Labels: enhancement
