Repository Theseus-Aegis/TheseusServices, pull requests merged in 2020-03, with the labels that each got.

#126 Remove Rear Gunner fix
  optionals/arcadian/CfgVehicles.hpp
Labels: enhancement

#127 Add Black Camo MX Magazine retexture
  addons/weapons/CfgMagazineWells.hpp
  addons/weapons/CfgMagazines.hpp
  addons/weapons/config.cpp
  addons/weapons/stringtable.xml
Labels: bug fix, feature request

#128 Arcadian - Fix side mounts removal
  optionals/arcadian/CfgVehicles.hpp
Labels: bug fix

#129 Arcadian - Fix side mounts removal (proper)
  optionals/arcadian/CfgVehicles.hpp
Labels: bug fix
