Repository Theseus-Aegis/TheseusServices, pull requests merged in 2021-02, with the labels that each got.

#150 Add A-TACS X Uniforms
  addons/units/CfgVehicles.hpp
  addons/units/CfgVehicles_GroundItems.hpp
  addons/units/CfgVehicles_HelperUnits.hpp
  addons/units/CfgWeapons.hpp
  addons/units/UI/uniform_combat_ls_atacs_atx.paa
  addons/units/UI/uniform_combat_ls_atacs_aux.paa
  addons/units/UI/uniform_combat_ls_atacs_ix.paa
  addons/units/UI/uniform_combat_ls_atacs_lex.paa
  addons/units/UI/uniform_combat_rs_atacs_atx.paa
  addons/units/UI/uniform_combat_rs_atacs_aux.paa
  addons/units/UI/uniform_combat_rs_atacs_ix.paa
  addons/units/UI/uniform_combat_rs_atacs_lex.paa
  addons/units/config.cpp
  addons/units/data/uniform_combat_atacs_atx_co.paa
  addons/units/data/uniform_combat_atacs_aux_co.paa
  addons/units/data/uniform_combat_atacs_ix_co.paa
  addons/units/data/uniform_combat_atacs_lex_co.paa
  addons/units/stringtable.xml
Labels: feature request

#151 Units - Organise file structure
  addons/units/CfgVehicles.hpp
  addons/units/CfgVehicles_GroundItems.hpp
  addons/units/CfgVehicles_HelperUnits.hpp
  addons/units/CfgVehicles_SupplyBox.hpp
  addons/units/CfgWeapons.hpp
  addons/units/config.cpp
  addons/units/data/uniform_combat.rvmat
  addons/units/items/base_helpers.hpp
  addons/units/items/base_item.hpp
  addons/units/items/combat_long_atacs_helpers.hpp
  addons/units/items/combat_long_atacs_item.hpp
  addons/units/items/combat_long_helpers.hpp
  addons/units/items/combat_long_item.hpp
  addons/units/items/combat_long_plaid_helpers.hpp
  addons/units/items/combat_long_plaid_item.hpp
  addons/units/items/combat_rolled_atacs_helpers.hpp
  addons/units/items/combat_rolled_atacs_item.hpp
  addons/units/items/combat_rolled_helpers.hpp
  addons/units/items/combat_rolled_item.hpp
  addons/units/items/combat_rolled_plaid_helpers.hpp
  addons/units/items/combat_rolled_plaid_item.hpp
  addons/units/items/floral_jeans_helpers.hpp
  addons/units/items/floral_jeans_item.hpp
  addons/units/items/floral_shorts_helpers.hpp
  addons/units/items/floral_shorts_item.hpp
  addons/units/items/garment_long_helpers.hpp
  addons/units/items/garment_long_item.hpp
  addons/units/items/garment_rolled_helpers.hpp
  addons/units/items/garment_rolled_item.hpp
  addons/units/items/plaid_jeans_helpers.hpp
  addons/units/items/plaid_jeans_item.hpp
  addons/units/items/plaid_shorts_helpers.hpp
  addons/units/items/plaid_shorts_item.hpp
  addons/units/items/polo_cord_helpers.hpp
  addons/units/items/polo_cord_item.hpp
  addons/units/items/polo_tactical_helpers.hpp
  addons/units/items/polo_tactical_item.hpp
  addons/units/items/tshirt_jeans_helpers.hpp
  addons/units/items/tshirt_jeans_item.hpp
  addons/units/items/vip_suit_item.hpp
  addons/units/stringtable.xml
  addons/units/uniforms/base.hpp
  addons/units/uniforms/combat_long.hpp
  addons/units/uniforms/combat_long_atacs.hpp
  addons/units/uniforms/combat_long_plaid.hpp
  addons/units/uniforms/combat_rolled.hpp
  addons/units/uniforms/combat_rolled_atacs.hpp
  addons/units/uniforms/combat_rolled_plaid.hpp
  addons/units/uniforms/floral_jeans.hpp
  addons/units/uniforms/floral_shorts.hpp
  addons/units/uniforms/garment_long.hpp
  addons/units/uniforms/garment_rolled.hpp
  addons/units/uniforms/plaid_jeans.hpp
  addons/units/uniforms/plaid_shorts.hpp
  addons/units/uniforms/polo_cord.hpp
  addons/units/uniforms/polo_tactical.hpp
  addons/units/uniforms/tshirt_jeans.hpp
  addons/units/uniforms/vip_suit.hpp
Labels: enhancement

#152 Units - Custom Material & SMDI for ATACS uniforms
  addons/units/data/uniform_combat_atacs.rvmat
  addons/units/data/uniform_combat_atacs_smdi.paa
  addons/units/items/base_helpers.hpp
  addons/units/items/combat_long_atacs_helpers.hpp
  addons/units/items/combat_rolled_atacs_helpers.hpp
Labels: enhancement

#153 Insignia - Remove racist patches
  addons/insignias/CfgUnitInsignia.hpp
  addons/insignias/data/infidel.paa
  addons/insignias/data/infidel2.paa
  addons/insignias/data/infidelnation.paa
  addons/insignias/data/joinordie.paa
  addons/insignias/data/matchmaker.paa
  addons/insignias/data/porkeatingcrusader.paa
  addons/insignias/data/porkeatingcrusader_tan.paa
  addons/insignias/data/waterboardingisbaptism.paa
Labels: cleanup

#155 Add more Insignias
  addons/insignias/CfgUnitInsignia.hpp
  addons/insignias/config.cpp
  addons/insignias/data/brandofsacrifice.paa
  addons/insignias/data/bridgefour.paa
  addons/insignias/data/iamunstoppable.paa
  addons/insignias/data/judge.paa
  addons/insignias/data/naturaltwenty.paa
  addons/insignias/data/neverforget.paa
  addons/insignias/data/raptorsquad.paa
Labels: feature request
