Repository Theseus-Aegis/TheseusServices, pull requests merged in 2021-11, with the labels that each got.

#182 Vehicles - Fix Eden Editor Asset Previews color grading
  addons/vehicles/UI/Polaris_AT_Black.jpg
  addons/vehicles/UI/Polaris_AT_Green.jpg
  addons/vehicles/UI/Polaris_AT_Tan.jpg
  addons/vehicles/UI/Polaris_Armed_Black.jpg
  addons/vehicles/UI/Polaris_Armed_Green.jpg
  addons/vehicles/UI/Polaris_Armed_Tan.jpg
  addons/vehicles/UI/Polaris_Black.jpg
  addons/vehicles/UI/Polaris_Green.jpg
  addons/vehicles/UI/Polaris_Tan.jpg
  addons/vehicles/UI/Van_Cargo_Black.jpg
  addons/vehicles/UI/Van_Transport_Black.jpg
Labels: bug fix

#180 Add Theseus RHIB
  addons/vehicles/CfgVehicles.hpp
  addons/vehicles/UI/RHIB_Theseus_Black.jpg
  addons/vehicles/config.cpp
  addons/vehicles/data/rhib_ext_co.paa
  addons/vehicles/data/rhib_int02_co.paa
  addons/vehicles/vehicles/rhib.hpp
Labels: feature request

#183 Add Theseus Colours to Main & Convert BWA to CSTRING
  addons/main/stringtable.xml
  addons/vehicles/vehicles/offroad.hpp
  addons/vehicles/vehicles/rhib.hpp
  addons/vehicles/vehicles/van.hpp
  optionals/variants_bwa3/CfgVehicles.hpp
  optionals/variants_bwa3/stringtable.xml
Labels: enhancement

#184 Units - Increase supply space inside combat uniforms
  addons/units/uniforms/base.hpp
Labels: enhancement
