Repository Theseus-Aegis/TheseusServices, pull requests merged in 2021-05, with the labels that each got.

#161 Alphapetize Insignia
  addons/insignias/CfgUnitInsignia.hpp
Labels: cleanup

#163 Units - Fix ATACS AT-X uniform name
  addons/units/stringtable.xml
Labels: bug fix

#164 Workflow - Replace Travis with GitHub CI
  .github/workflows/ci.yml
  .travis.yml
  AUTHORS.txt
Labels: tools

#162 Vehicles - Expand Offroads
  addons/vehicles/CfgVehicles.hpp
  addons/vehicles/data/offroad_theseus_black_ext_co.paa
Labels: bug fix, enhancement, feature request
