Repository Theseus-Aegis/TheseusServices, pull requests merged in 2022-10, with the labels that each got.

#193 Vehicles - Fix HEMTT Editor Previews
  addons/vehicles/vehicles/hemtt.hpp
Labels: bug fix

#194 Vehicles - Add Black Covered Offroad retexture
  addons/vehicles/UI/Offroad_Covered_Black.jpg
  addons/vehicles/data/offroad_black_cover_ext_co.paa
  addons/vehicles/stringtable.xml
  addons/vehicles/vehicles/offroad.hpp
Labels: feature request

#195 Vehicles - Fix missing baseclass (XEH) for Covered Offroad
  addons/vehicles/vehicles/offroad.hpp
Labels: bug fix

#196 Backpacks - Add White Carryall Backpack
  addons/backpacks/CfgVehicles.hpp
  addons/backpacks/UI/backpack_carryall_white_ca.paa
  addons/backpacks/config.cpp
  addons/backpacks/data/backpack_carryall_white_co.paa
  addons/backpacks/stringtable.xml
Labels: feature request

#198 Main - Update loadorder to AoW
  addons/main/config.cpp
Labels: task
