Repository Theseus-Aegis/TheseusServices, pull requests merged in 2023-08, with the labels that each got.

#212 Units - Add more Theseus Contractor names
  addons/units/CfgWorlds.hpp
Labels: enhancement

#214 Vehicles - Add Theseus Merlin
  addons/vehicles/CfgVehicles.hpp
  addons/vehicles/UI/Heli_Merlin.jpg
  addons/vehicles/config.cpp
  addons/vehicles/data/heli_transport_02_1_theseus_co.paa
  addons/vehicles/data/heli_transport_02_2_theseus_co.paa
  addons/vehicles/data/heli_transport_02_3_theseus_co.paa
  addons/vehicles/stringtable.xml
  addons/vehicles/vehicles/merlin.hpp
Labels: feature request

#215 Arcadian - Remove Theseus Mods Heavy Lifter config
  addons/arcadian/base/config_misc.hpp
Labels: cleanup

#216 General - Streamline branding
  .hemtt/hooks/post_release/01_rename_zip.rhai
  .hemtt/project.toml
  addons/main/$PBOPREFIX$
  addons/main/stringtable.xml
  mod.cpp
Labels: cleanup

#218 Backpacks - Add new Grey variants
  addons/backpacks/CfgVehicles.hpp
  addons/backpacks/UI/backpack_assaultexpanded_grey_ca.paa
  addons/backpacks/UI/backpack_assaultpack_grey_ca.paa
  addons/backpacks/UI/backpack_kitbag_grey_ca.paa
  addons/backpacks/config.cpp
  addons/backpacks/data/backpack_assaultexpanded_grey_co.paa
  addons/backpacks/data/backpack_kitbag_grey_co.paa
  addons/backpacks/stringtable.xml
  addons/vests/CfgVehicles.hpp
  addons/vests/CfgWeapons.hpp
  addons/vests/UI/vest_platecarrier_grey_ca.paa
  addons/vests/config.cpp
  addons/vests/data/vest_platecarrier_grey_co.paa
  addons/vests/stringtable.xml
Labels: feature request
